name: Package controller-runtime envtest

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'hack/envtest/_matrix/*.yaml'

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # tag=v4.1.5
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@0874344d6ebbaa00a27da73276ae7162fadcaf69 # tag=v44.3.0
        with:
          files: |
            hack/envtest/_matrix/*.yaml
      - name: Setup package release version
        id: release-version
        run: |
            if [[ ${{ steps.changed-files.outputs.all_changed_files_count }} != 1 ]]; then
              echo "One Kubernetes patch version files should be changed for a release, found ${{ steps.changed-files.outputs.all_changed_files_count }}"
              exit 1
            fi

            for changed_file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              export KUBERNETES_VERSION=$(echo "${changed_file}" | grep -oP '(?<=/)[^/]+(?=\.yaml)')
              echo "KUBERNETES_VERSION=$KUBERNETES_VERSION" >> $GITHUB_ENV
            done
      - name: Build packages
        run: |
          make release-envtest KUBERNETES_VERSION=${{ env.KUBERNETES_VERSION }}
      - name: Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564 # tag=v2.0.4
        with:
          tag_name: envtest-${{ env.KUBERNETES_VERSION }}
          draft: false
          make_latest: false
          files: |
            out/envtest-*.tar.gz
            out/envtest-*.tar.gz.sha512
          fail_on_unmatched_files: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e # tag=v6.0.5
        with:
          commit-message: Promote envtest release for Kubernetes ${{ env.KUBERNETES_VERSION }}
          title: ":seedling: Promotion of envtest release for Kubernetes ${{ env.KUBERNETES_VERSION }}"
          body: |
            This PR promotes the envtest release for Kubernetes ${{ env.KUBERNETES_VERSION }}.
          branch: promote-envtest-${{ env.KUBERNETES_VERSION }}
          add-paths: |
            envtest-releases.yaml
